# Generated by Django 5.0.3 on 2024-03-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Subscribed_to',
            new_name='subscribed_to',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Subscriber',
            new_name='subscriber',
        ),
    ]
